--liquibase formatted sql

--changeset denis:1
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP
);

CREATE TABLE perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(255),
    biografia TEXT,
    imagem_url VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    usuario_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_perfil_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE projeto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    imagem_capaurl VARCHAR(255),
    data_pub DATE,
    perfil_id BIGINT NOT NULL,
    CONSTRAINT fk_projeto_perfil FOREIGN KEY (perfil_id) REFERENCES perfil(id)
);

CREATE TABLE comentario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto TEXT NOT NULL,
    data_criacao TIMESTAMP,
    usuario_id BIGINT NOT NULL,
    projeto_id BIGINT NOT NULL,
    CONSTRAINT fk_comentario_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT fk_comentario_projeto FOREIGN KEY (projeto_id) REFERENCES projeto(id)
);